### ISSUE TITLE
NFS-e Belo Horizonte

### ISSUE THREAD

**Issue by domhost** [nfephp-org/sped-nfse#100]
Boa noite amigo,

Tem previsão de quando a NFS-e vai estar funcional pra Belo Horizonte?

Abraços.

**Comment by robmachado** [comment]
Sem previsão ... a ordem do desenvolvimento depende de doações de $$ e do envio de material técnico como certificados para realizar os testes. Por ora estão previstos Prodam (beta teste), São Luis, Rio de Janeiro e Salvador. Nada mais tenho em foco.

**Comment by domhost** [comment]
Quanto vcs cobrariam pra fazer o de BH primeiro e qual seria a funcionalidade?

**Comment by robmachado** [comment]
Não é cobrado nada para fazer !! isso é uma doação apenas.
Se fosse cobrar mesmo seria bem caro em virtude do numero de horas envolvido nisso, para te dar uma idéia o modelo Prodam (São Paulo)  envolveu mas de 80 horas .
Essa doação refere-se apenas a uma ajuda de custo, para que se possa dedicar mais tempo a um determinado projeto que será liberado como LGPL.
Tenho recebido umas poucas doações. Mas giram em torno de R$ 1500 por prefeitura ... quanto a funcionalidade seriam TODAS disponibilizadas pelo webservice do município. Ainda devo lembra-lo que isso requer tempo e testes com um certificado válido. Apesar de parecer simples a NFSe é muito mais complexa que o modelo da SEFAZ.

**Comment by domhost** [comment]
Entendi. Eu estava querendo pelo menos enviar a NFSe por meio de lote no proprio sistema da PBH, mas pra isso o RPD precisa ser assinado. Cheguei a usar o NFe desenvolvido por você pra fazer essa assinatura, mas deu erro, pois além de assinar cada NF, tem que assinar o RPD inteiro tb. Vc poderia me dar um caminho sobre como eu faço pra assinar o XML pra enviar via web?
Tb tenho conhecimento em PHP e se vc me der uma ajuda nessa parte de assinatura, poderei eu mesmo fazer essa parte.

Abraços.

**Comment by robmachado** [comment]
veja os códigos nesse repositório
