### ISSUE TITLE
NFS-e RJ

### ISSUE THREAD

**Issue by zabaala** [nfephp-org/sped-nfse#150]
Bom dia!

Estou precisando emitir nota para o Rio e, pelo que vi, não há suporte ainda. Por esse motivo, estou me colocando à disposição para desenvolver o que for necessário, mas confesso que não tenho experiência com geração de notas fiscais e não sei o quão grande será a dificuldade pra isso. 

Por termos essa necessidade (e bastante vontade de contribuir com a comunidade), internamente aqui na empresa, nós resolvemos nos dedicar a estas implementações e também estamos contando com o apoio do nosso setor contábil para o que for necessário. 

Com isso, podemos contar com a ajuda de vocês para nos darem alguns direcionamentos? Se sim, por onde começamos?

Um abraço!

**Comment by robmachado** [comment]
Conforme informado pelo portal do SPED em dezembro deveriam ser disponibilizadas a documentação do **NFSe Nacional** que iniciaria pelas cidades de:
- Porto Alegre;
- Rio de Janeiro;
- São Paulo;
- Brasília;
- Maringá;
- Marabá;
- Belo Horizonte.
Porém até o momento isso está uma **verdadeira confusão**. Minha sugestão é que antes de gastar tempo e esforços entrem em contato com algum TÉCNICO da Prefeitura e questionem sobre isso. Caso contrario podem ter seus esforços jogados no LIXO !

**Comment by zabaala** [comment]
Farei isso agora, @robmachado! 

Obrigado pela resposta. Volto em breve com respostas sobre isso.

**Comment by luizcarlospedrosogomes** [comment]
@zabaala alguma novidade sobre a integração com a cidade do rio?

**Comment by robmachado** [comment]
No site dizem que é compativel com o modelo nacional.
Se isso for verdade, basta incluir algumas informações no pacote [sped-nfse-nacional ](https://github.com/nfephp-org/sped-nfse-nacional)

**Comment by luizcarlospedrosogomes** [comment]
@robmachado obrigado, vou testar e retorno aqui sobre as alterações realizadas. No caso de novas duvidas sobre o pacote eu abro uma issues la no repositorio.

**Comment by zabaala** [comment]
> @zabaala alguma novidade sobre a integração com a cidade do rio?
@luizcarlospedrosogomes acabei contratando um serviço e me integrei a ele. Foi mais rápido e menos oneroso pra equipe.

**Comment by luizcarlospedrosogomes** [comment]
@zabaala obrigado. mas vamos usar o repositorio para escalar.
