### ISSUE TITLE
Substituir o RPS pela NFS-e

### ISSUE THREAD

**Issue by Gerlis** [nfephp-org/sped-nfse#167]
é possível fazer a substituir o RPS pela NFS-e nessa api?

**Comment by robmachado** [comment]
Esta API está descontinuada !! 
Outras foram criadas para alguns modelos

**Comment by robmachado** [comment]
https://github.com/nfephp-org/sped-nfse/blob/master/README.md

**Comment by Gerlis** [comment]
Há blz, obrigado mais ainda não tem projeto para SP capital?
Se será que posso trabalha com algum desses já criado e adaptar para São Paulo?
