### ISSUE TITLE
Integração com a prefeitura do Natal RN.

### ISSUE THREAD

**Issue by EdvaldoLima** [nfephp-org/sped-nfse#173]
Caros colegas gostaria de saber se já existe previsão ou conversa formal para a integração. Dado a tamanha complexidade desse projeto posso está fazendo um pergunta retórica, porém posso fazer essa ponte para integrar a capital do RN ao projeto caso ainda não exista conversa formal.

**Comment by robmachado** [comment]
Este projeto está descontinuado !
Devido a ENORME complexidade, estou quando possível, desmembrando em projetos separados para cada MODELO de NFSe.
Não é viável manter projeto OpenSource para as NFSe devido a falta de colaboração. É trabalhoso demais, muitas vezes muito complexo e sem nenhuma ajuda fica impossível.
Minha recomendação, use um dos serviços restful já existentes é pago mas dá muito menos trabalho.

**Comment by EdvaldoLima** [comment]
@robmachado compreendo demais, infelizmente a ideia que temos das notas nos municípios é que foi "implementado" nas "coxas", estava até cogitando com um colega a construção de algo para o RN pra facilitar a vida mas a complexidade é surreal, de qualquer forma agradeço pelo retorno.

Abraço.
